spring.application.name=produto-service
spring.profiles.default=dev

pring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.probes.enabled=true
management.health.rabbit.enabled=true
management.info.env.enabled=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.api.pagination.default-size=20
app.api.pagination.max-size=100
app.messaging.retry.ttl-ms=30000
app.outbox.retry-delay-ms=30000
app.outbox.auto-publish=true